get https://go-order-service-220652406095.us-central1.run.app/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlci0wMDEiLCJleHAiOjE3NTExMjE4MzQsImlhdCI6MTc1MDc3NjIzNH0.ePWmTLto1ASeQBN_Dm8Fc9kYF0qmgtCpl5_mfCgvOTc